### ISSUE TITLE
Can esp32-s3-zero replace esp32s3sense?

### ISSUE THREAD

**Issue by zhuwei** [RomanLut/hx-esp32-cam-fpv#7]
If possible, how do I wire it? For example, D0? How to connect the ov5640?

**Comment by zhuwei** [comment]
It seems that configuration needs to be added in main. h

**Comment by zhuwei** [comment]
After checking some information, it seems that ESP32S3 Sense is more suitable. But with the addition of ov5640, the price is too expensive. Not as cost-effective as OpenIPC

**Comment by zhuwei** [comment]
I have a question, is PSRAM important? If it's not important, esp32-fh4r2 should also be able to handle it, right?

**Comment by geofrancis** [comment]
> After checking some information, it seems that ESP32S3 Sense is more suitable. But with the addition of ov5640, the price is too expensive. Not as cost-effective as OpenIPC

openIPC cameras are still very large, at least 4x the size of a esp32sense.

**Comment by RomanLut** [comment]
> If possible, how do I wire it? For example, D0? How to connect the ov5640?

You will not be able to connect camera to board without camera connector.

**Comment by RomanLut** [comment]
> I have a question, is PSRAM important? If it's not important, esp32-fh4r2 should also be able to handle it, right?

Yes PSRAM is important. As side note - the goal of the project is to take available module, flash it and use. It is better to pay few bucks then solder anything.

**Comment by RomanLut** [comment]
> After checking some information, it seems that ESP32S3 Sense is more suitable. But with the addition of ov5640, the price is too expensive. Not as cost-effective as OpenIPC

As mentioned in the description, the goal of the project (apart academic interest) is to develop FPV system for small UAVs. I am flying tiny 1S wings like Ldark Tiny wing, where OpenIPC system based on standart 38x38 security camera simply does not fit by size, weight and power consumption. So in my case I have to compare esp32s3sense price to custom OpenIPC hardware which costs $100 and required expensive pololu syncronous 2A stepup conveter $10. 

If you can fit 38x38 camera on your frame, I suggest to go with OpenIPC which is much superior in image quality compared to esp.

![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/1562ab06-4dd4-4627-b2a7-46be36cecec7)

**Comment by zhuwei** [comment]
1280* 720@30fps Can the minimum delay reach 30ms?

**Comment by RomanLut** [comment]
> 1280* 720@30fps Can the minimum delay reach 30ms?

Sorry there was error in readme, current latency is 90-110ms for all resolutions, tested with Skyzone 03O glasses. This is still to be investigated because expected latency should be in range 50-70ms. I did not work on latency improvement yet.

I think for 30ms latency,  frames has to be captured at 90 or 120 fps  which esp can not do. ~50ms with 800x456x50 theoretically is acheavable. 

As side note, 1280x720x30 requires too high mjpeg bandwidth and looks worse then 1024x576. As using 1280x720 for fpv is not practical,  in the next release 1280x720 will work in HQDVR mode: video will be saved to SD with maximum possible quality on air unit and sent to gs with low fps ~10. The purpose is to give possibility to record decent quality videos.

**Comment by Ncerzzk** [comment]
> 1280* 720@30fps Can the minimum delay reach 30ms?

even you do nothing, the frame interval will be 1000s / 30 frame = 33ms/frame, so it's impossiable.

**Comment by zhuwei** [comment]
@RomanLut @Ncerzzk Thank you, I'm not sure if it's possible to replace it with a cheaper esp32-s3-zero? If you want to replace it, you probably need to draw your own expansion board

**Comment by RomanLut** [comment]
I am not sure that making expansion board is possible because not all pins are available on zero board. Expansion board should have camera connector, sdcard slot and  psram. If I would make a module, I would make it from scratch. But it is too much trouble for a few $. 

A lot of other camera boards could be supported, but I provide support for esp32cam and esps3s3sense only. esp32cam is something usually lying around after experiments, esp32s3sense is board to use on micro uav.

esp32 m5stack timer  cam:

![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/f78a57c1-af7a-43a7-b6f2-8e0065aa2f75)

esp32 m5stack unit cam:
![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/63596667-2579-4774-b289-48864480ece2)


esp32-eye:
![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/80d55487-e107-4369-a9a2-02490f44c035)



esp32-s3 wroom:
![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/6dafe764-e4c8-4ec8-b354-7e9f3c1fcdf5)

esp32-s3-cam:
![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/b08ac3b4-010a-4e88-951b-fabdccf31993)

esp32-s3 eye:
![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/7d365103-47d9-452a-800a-f2a29caa0c41)

m5 unit cam s3:
![image](https://github.com/RomanLut/hx-esp32-cam-fpv/assets/11955117/f046ea48-816b-46c1-8675-4d792bdf18a4)

**Comment by zhuwei** [comment]
Understood, thank you for your reply!
